"""empty message

Revision ID: 13eab8a56ef8
Revises: bacf8aba7ff7
Create Date: 2025-08-29 02:01:58.223783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13eab8a56ef8'
down_revision: Union[str, Sequence[str], None] = 'bacf8aba7ff7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('naver_id', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'user', ['naver_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'naver_id')
    # ### end Alembic commands ###
